### PR TITLE
call `dbsuper.isUnrealType` instead of testing for function presence

### PR DESCRIPTION
**Pull request by XertroV**
I guess this is meant to be called.

### CODE REVIEW

**Comment by GGLucas** [comment]
Good catch, that was definitely unintended. Thanks for the fix 👍

**Comment by XertroV** [comment]
yw :)

FYI: I'm developing a fork for use with [openplanet](https://openplanet.dev)'s flavor of angelscript ([code](https://github.com/XertroV/vscode-openplanet-angelscript/)). If I find anything like the above I'll be sure to make an issue/PR.

There are some things I've found and fixed, like superclasses in a namespace (e.g., `class SomeClass : Lib::BaseClase {}`) didn't resolve properly and namespaces where parsed out of symbols. But I guess that some of these things are unimplemented b/c they aren't common in your environment. My implementations might not suit your style, esp b/c I am hacking at it so for complex stuff like this I probably won't PR them. (Not to mention that it sometimes touches syntax stuff and IDK what the effects of those changes will be.) But you're welcome to copy-paste any code of mine that you like. I've added a changelog / list of features to to the readme so that will give you an idea of what I've done if you're curious.

**Comment by GGLucas** [comment]
Oh, very nice! Glad you're finding some unexpected use for the code here :D

For the namespace stuff, specifying a superclass that's in a namespace isn't actually supported by the unreal integration at all right now.

There's a couple of limitations to namespaces related to that. Unreal types don't support namespaces, so the name of a type needs to be unique even if it's in a different script namespace.
The extension uses that fact as an assumption in a few places to avoid extra namespace logic.

That's also why symbols ignore namespaces - the symbol_name should never contain a namespace, it should only contain the non-qualified typename which is required to be unique due to unreal.

Definitely going to poke around your code changes out of curiosity, but your approach for only PRing back very obvious small fixes like this sounds like the right way ahead. The angelscript flavor being used by this plugin is quite divergent from vanilla as I'm sure you've found.

**Comment by XertroV** [comment]
> Glad you're finding some unexpected use for the code here :D

As am I :). I'm grateful for all the heavy lifting.

> The extension uses that fact as an assumption in a few places to avoid extra namespace logic.

Ahh! Good to know.

> The angelscript flavor being used by this plugin is quite divergent from vanilla as I'm sure you've found.

Yes.
As an FYI: In my fork, I've commented out a lot of unreal stuff (in part due to not needing it and debugging, and in part due to incompatible keywords etc). I am not sure of the major differences between unreal-angelscript's flavor and openplanet's, but I use <https://www.angelcode.com/angelscript/sdk/docs/manual/doc_script.html> as a reference often, and it all seems consistent (so I'm working from that). Some of my changes reflect that, e.g., `get_`/`set_` accessors. (related btw, there's a typo in `DBType.acccessSpecifiers` but i guess that's legacy now :P)

**Pull request merged**
